"""Report generator - submittal reports, equipment schedules, point summaries."""

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import pandas as pd

from ..models import Project, Protocol


@dataclass
class ReportSection:
    """A section of a report."""
    title: str
    content: str
    level: int = 2  # markdown heading level


class ReportGenerator:
    """Generates engineering reports from project data."""

    def __init__(self, project: Project):
        self.project = project

    def _review_summary_lines(self) -> list[str]:
        state = self.project.review_state
        assumption_counts: dict[str, int] = {}
        for assumption in state.assumptions:
            assumption_counts[assumption.status] = assumption_counts.get(assumption.status, 0) + 1
        resolved_gap_count = sum(1 for decision in state.gap_decisions if decision.status == "resolved")
        approved_outputs = next(
            (
                approval
                for approval in state.approvals
                if approval.approval_key == "outputs-ready" and approval.status == "approved"
            ),
            None,
        )

        lines = [
            "## Review Decisions",
            f"- Assumptions captured: **{len(state.assumptions)}**",
            f"- Gap resolutions recorded: **{resolved_gap_count}**",
            f"- Mapping decisions recorded: **{len(state.mapping_decisions)}**",
            f"- Output approval: **{'approved' if approved_outputs else 'pending'}**",
        ]
        for status, count in sorted(assumption_counts.items()):
            lines.append(f"- Assumptions {status}: {count}")
        if approved_outputs and approved_outputs.notes:
            lines.append(f"- Output approval notes: {approved_outputs.notes}")
        return lines

    def generate_equipment_schedule(self, output_path: Path) -> Path:
        """Generate equipment schedule report (Excel)."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        rows = []
        for equip in self.project.equipment:
            effective_controller_id = self.project.effective_equipment_controller_id(equip)
            controller = self.project.get_controller(effective_controller_id) if effective_controller_id else None
            points = self.project.get_points_for_equipment(equip.id)

            point_counts = {}
            for p in points:
                point_counts[p.kind.value] = point_counts.get(p.kind.value, 0) + 1

            rows.append({
                "Equipment ID": equip.id,
                "Type": equip.type.value,
                "Subtype": equip.subtype or "",
                "Building": equip.building or "",
                "Floor": equip.floor or "",
                "Room": equip.room or "",
                "Served Area": equip.served_area or "",
                "Controller": effective_controller_id or "Unassigned",
                "Controller Vendor": controller.vendor if controller else "",
                "Controller Model": controller.model if controller else "",
                "Design CFM": equip.design_cfm or "",
                "Design Tonnage": equip.design_tonnage or "",
                "Design GPM": equip.design_gpm or "",
                "Design kW": equip.design_kw or "",
                "Voltage": equip.voltage or "",
                "Phase": equip.phase or "",
                "Status": equip.status,
                "Total Points": len(points),
                **{f"Points - {k.title()}": v for k, v in point_counts.items()},
            })

        df = pd.DataFrame(rows)
        with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
            df.to_excel(writer, sheet_name="Equipment Schedule", index=False)

            # Add metadata sheet
            meta = pd.DataFrame([{
                "Project": self.project.metadata.name,
                "Project ID": self.project.metadata.project_id,
                "Client": self.project.metadata.client or "",
                "Location": self.project.metadata.location or "",
                "Unit System": self.project.metadata.unit_system.value,
                "Generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
                "Generated By": "BAS Assistant",
            }])
            meta.to_excel(writer, sheet_name="Project Info", index=False)

        return output_path

    def generate_point_schedule(self, output_path: Path) -> Path:
        """Generate point schedule report (Excel)."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        rows = []
        for point in self.project.points:
            effective_equipment_id = self.project.effective_point_equipment_id(point) or point.equipment_id
            effective_controller_id = self.project.effective_point_controller_id(point)
            equip = self.project.get_equipment(effective_equipment_id)
            controller = self.project.get_controller(effective_controller_id) if effective_controller_id else None

            rows.append({
                "Point Name": point.name,
                "Equipment": effective_equipment_id,
                "Equipment Type": equip.type.value if equip else "UNKNOWN",
                "Kind": point.kind.value,
                "Direction": point.direction.value,
                "Units": point.units or "",
                "Unit System": point.unit_system or self.project.metadata.unit_system.value,
                "Range Min": point.range_min or "",
                "Range Max": point.range_max or "",
                "Controller": effective_controller_id or "Unassigned",
                "Controller Vendor": controller.vendor if controller else "",
                "BACnet Object Type": point.bacnet_object_type or "",
                "BACnet Instance": point.bacnet_instance or "",
                "Modbus Register": point.modbus_register or "",
                "Modbus Type": point.modbus_type or "",
                "Source": point.source.value,
                "Source Reference": point.source_reference or "",
                "Validation Status": point.validation_status,
                "Description": point.description or "",
                "Tags": ", ".join(point.tags),
            })

        columns = [
            "Point Name", "Equipment", "Equipment Type", "Kind", "Direction",
            "Units", "Unit System", "Range Min", "Range Max", "Controller",
            "Controller Vendor", "BACnet Object Type", "BACnet Instance",
            "Modbus Register", "Modbus Type", "Source", "Source Reference",
            "Validation Status", "Description", "Tags",
        ]
        df = pd.DataFrame(rows, columns=columns)
        with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
            df.to_excel(writer, sheet_name="Point Schedule", index=False)

            if df.empty:
                pd.DataFrame(columns=["Equipment", "Total"]).to_excel(writer, sheet_name="Point Summary", index=False)
                pd.DataFrame(columns=["Controller", "Total"]).to_excel(writer, sheet_name="By Controller", index=False)
            else:
                # Summary pivot
                summary = df.groupby(["Equipment", "Kind"]).size().unstack(fill_value=0)
                summary["Total"] = summary.sum(axis=1)
                summary.to_excel(writer, sheet_name="Point Summary")

                # By controller
                ctrl_summary = df.groupby(["Controller", "Direction"]).size().unstack(fill_value=0)
                ctrl_summary["Total"] = ctrl_summary.sum(axis=1)
                ctrl_summary.to_excel(writer, sheet_name="By Controller")

        return output_path

    def generate_controller_schedule(self, output_path: Path) -> Path:
        """Generate controller schedule report (Excel)."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        rows = []
        for ctrl in self.project.controllers:
            points = self.project.get_points_for_controller(ctrl.id)
            equip = self.project.get_equipment_for_controller(ctrl.id)
            ip_addresses = [
                address.address
                for address in ctrl.network_addresses
                if address.protocol == Protocol.BACNET_IP
            ]
            mstp_macs = [
                address.address
                for address in ctrl.network_addresses
                if address.protocol == Protocol.BACNET_MSTP
            ]
            network_numbers = sorted(
                {
                    str(address.network_number)
                    for address in ctrl.network_addresses
                    if address.network_number is not None
                }
            )

            point_counts = {}
            for p in points:
                point_counts[p.kind.value] = point_counts.get(p.kind.value, 0) + 1

            io = ctrl.io_capacity
            utilization = ctrl.utilization_pct() if io else None

            rows.append({
                "Controller ID": ctrl.id,
                "Name": ctrl.name or "",
                "Vendor": ctrl.vendor or "",
                "Model": ctrl.model or "",
                "Firmware": ctrl.firmware_version or "",
                "Type": ctrl.type,
                "Protocols": ", ".join(p.value for p in ctrl.protocols),
                "IP Addresses": ", ".join(ip_addresses),
                "MS/TP MACs": ", ".join(mstp_macs),
                "Network Numbers": ", ".join(network_numbers),
                "Panel Location": ctrl.panel_location or "",
                "Electrical Panel": ctrl.electrical_panel or "",
                "Circuit": ctrl.circuit or "",
                "Serves Equipment": ", ".join(self.project.effective_controller_serves_equipment_ids(ctrl)),
                "Equipment Count": len(equip),
                "Owned Points": len(points),
                **{f"Points - {k.title()}": v for k, v in point_counts.items()},
                "UI Capacity": io.universal_inputs if io else "",
                "DI Capacity": io.digital_inputs if io else "",
                "AO Capacity": io.analog_outputs if io else "",
                "DO Capacity": io.digital_outputs if io else "",
                "Total Capacity": io.total_points if io else "",
                "Utilization %": round(utilization, 1) if utilization else "",
                "Status": ctrl.status,
            })

        df = pd.DataFrame(rows)
        with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
            df.to_excel(writer, sheet_name="Controller Schedule", index=False)

            # Network summary
            net_rows = []
            for ctrl in self.project.controllers:
                for addr in ctrl.network_addresses:
                    net_rows.append({
                        "Controller": ctrl.id,
                        "Protocol": addr.protocol.value,
                        "Address": addr.address,
                        "Network #": addr.network_number or "",
                    })
            if net_rows:
                pd.DataFrame(net_rows).to_excel(writer, sheet_name="Network Addresses", index=False)

        return output_path

    def generate_submittal_package(self, output_dir: Path) -> dict:
        """Generate complete submittal package (multiple files)."""
        output_dir.mkdir(parents=True, exist_ok=True)

        paths = {}

        # Equipment schedule
        paths["equipment_schedule"] = self.generate_equipment_schedule(
            output_dir / "01_Equipment_Schedule.xlsx"
        )

        # Point schedule
        paths["point_schedule"] = self.generate_point_schedule(
            output_dir / "02_Point_Schedule.xlsx"
        )

        # Controller schedule
        paths["controller_schedule"] = self.generate_controller_schedule(
            output_dir / "03_Controller_Schedule.xlsx"
        )

        # Project summary markdown
        paths["summary"] = self.generate_project_summary_md(
            output_dir / "00_Project_Summary.md"
        )

        # Validation report if available
        if self.project.last_validated:
            paths["validation"] = self.generate_validation_report_md(
                output_dir / "04_Validation_Report.md"
            )

        return paths

    def generate_project_summary_md(self, output_path: Path) -> Path:
        """Generate markdown project summary."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        lines = [
            f"# {self.project.metadata.name}",
            f"**Project ID:** {self.project.metadata.project_id}",
            "",
            f"**Client:** {self.project.metadata.client or 'N/A'}",
            f"**Location:** {self.project.metadata.location or 'N/A'}",
            f"**Unit System:** {self.project.metadata.unit_system.value}",
            f"**Design Phase:** {self.project.metadata.design_phase or 'N/A'}",
            f"**Engineer of Record:** {self.project.metadata.engineer_of_record or 'N/A'}",
            f"**Programmer:** {self.project.metadata.programmer or 'N/A'}",
            f"**Cx Agent:** {self.project.metadata.commissioning_agent or 'N/A'}",
            "",
            "---",
            "",
            "## Counts",
            f"- Equipment: **{len(self.project.equipment)}**",
            f"- Points: **{len(self.project.points)}**",
            f"- Controllers: **{len(self.project.controllers)}**",
            f"- Source Documents: **{len(self.project.source_documents)}**",
            "",
            "## Equipment by Type",
        ]

        # Equipment by type
        equip_by_type = {}
        for e in self.project.equipment:
            equip_by_type[e.type.value] = equip_by_type.get(e.type.value, 0) + 1

        for typ, count in sorted(equip_by_type.items()):
            lines.append(f"- {typ}: {count}")

        lines.extend(["", "## Points by Kind"])

        points_by_kind = {}
        for p in self.project.points:
            points_by_kind[p.kind.value] = points_by_kind.get(p.kind.value, 0) + 1

        for kind, count in sorted(points_by_kind.items()):
            lines.append(f"- {kind.title()}: {count}")

        lines.extend(["", "## Controllers by Protocol"])

        proto_counts = {}
        for c in self.project.controllers:
            for p in c.protocols:
                proto_counts[p.value] = proto_counts.get(p.value, 0) + 1

        for proto, count in sorted(proto_counts.items()):
            lines.append(f"- {proto}: {count}")

        lines.extend([""] + self._review_summary_lines())
        lines.extend(["", "---", f"*Generated by BAS Assistant on {datetime.now().strftime('%Y-%m-%d %H:%M')}*"])

        with open(output_path, "w") as f:
            f.write("\n".join(lines))

        return output_path

    def generate_validation_report_md(self, output_path: Path) -> Path:
        """Generate markdown validation report (placeholder)."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        lines = [
            "# Validation Report",
            f"**Project:** {self.project.metadata.name} ({self.project.metadata.project_id})",
            f"**Last Validated:** {self.project.last_validated.strftime('%Y-%m-%d %H:%M') if self.project.last_validated else 'Never'}",
            f"**Status:** {self.project.validation_status}",
            "",
            "## Summary",
            f"- Total Equipment: {len(self.project.equipment)}",
            f"- Total Points: {len(self.project.points)}",
            f"- Total Controllers: {len(self.project.controllers)}",
            "",
            "## Checks Performed",
            "- Naming convention compliance",
            "- Completeness (equipment-controller-point relationships)",
            "- Consistency (cross-references, duplicates)",
            "- Engineering rules (ranges, units)",
            "- Protocol rules (BACnet instances, Modbus registers)",
            "",
            "## Recommendations",
            "1. Run `bas validate` to generate detailed report",
            "2. Address all ERROR severity issues before submittal",
            "3. Review WARNING items for engineering judgment",
            "",
            "---",
            f"*Generated by BAS Assistant on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        ]

        with open(output_path, "w") as f:
            f.write("\n".join(lines))

        return output_path


def generate_reports(project: Project, output_dir: Path) -> dict:
    """Convenience function to generate all reports."""
    generator = ReportGenerator(project)
    return generator.generate_submittal_package(output_dir)


__all__ = ["ReportGenerator", "generate_reports"]
